#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x87113ff9, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x4d405db8, __VMLINUX_SYMBOL_STR(param_ops_string) },
	{ 0x1976aa06, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0xb77ed698, __VMLINUX_SYMBOL_STR(trace_event_raw_init) },
	{ 0xccd58358, __VMLINUX_SYMBOL_STR(ftrace_event_reg) },
	{ 0xa140872e, __VMLINUX_SYMBOL_STR(single_release) },
	{ 0x53feaf5, __VMLINUX_SYMBOL_STR(seq_lseek) },
	{ 0xfbc655dd, __VMLINUX_SYMBOL_STR(driver_unregister) },
	{ 0x68b7955e, __VMLINUX_SYMBOL_STR(spi_register_driver) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xf3d32f50, __VMLINUX_SYMBOL_STR(usb_hcd_poll_rh_status) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xfbc74f64, __VMLINUX_SYMBOL_STR(__copy_from_user) },
	{ 0x1a08a063, __VMLINUX_SYMBOL_STR(pm_relax) },
	{ 0x16164a86, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0x107cc004, __VMLINUX_SYMBOL_STR(usb_remove_hcd) },
	{ 0x4c9a0e78, __VMLINUX_SYMBOL_STR(dev_get_drvdata) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0xe30294bb, __VMLINUX_SYMBOL_STR(pm_stay_awake) },
	{ 0x91c78069, __VMLINUX_SYMBOL_STR(device_init_wakeup) },
	{ 0x57487caf, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0x71f68403, __VMLINUX_SYMBOL_STR(__pm_runtime_set_status) },
	{ 0x61f1f92e, __VMLINUX_SYMBOL_STR(pm_runtime_no_callbacks) },
	{ 0x4ae58a93, __VMLINUX_SYMBOL_STR(debugfs_remove_recursive) },
	{ 0xeee32097, __VMLINUX_SYMBOL_STR(debugfs_create_file) },
	{ 0x9b655e0f, __VMLINUX_SYMBOL_STR(debugfs_create_dir) },
	{ 0xae969c12, __VMLINUX_SYMBOL_STR(usb_put_hcd) },
	{ 0xe0077b8a, __VMLINUX_SYMBOL_STR(usb_add_hcd) },
	{ 0xd230ce80, __VMLINUX_SYMBOL_STR(usb_create_hcd) },
	{ 0xda15ea2a, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x5e975d89, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0xd217e9e6, __VMLINUX_SYMBOL_STR(trace_set_clr_event) },
	{ 0xf0a3421f, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0xa0f04079, __VMLINUX_SYMBOL_STR(devm_gpio_request) },
	{ 0x135510fb, __VMLINUX_SYMBOL_STR(devm_pinctrl_put) },
	{ 0xcbe9ecb1, __VMLINUX_SYMBOL_STR(pinctrl_select_state) },
	{ 0xf0aef573, __VMLINUX_SYMBOL_STR(pinctrl_lookup_state) },
	{ 0x5882e0ac, __VMLINUX_SYMBOL_STR(devm_pinctrl_get) },
	{ 0x98cc564a, __VMLINUX_SYMBOL_STR(regulator_set_voltage) },
	{ 0xc77e0d30, __VMLINUX_SYMBOL_STR(devm_regulator_get) },
	{ 0x45ac0ff4, __VMLINUX_SYMBOL_STR(devm_clk_get) },
	{ 0x260cf8f8, __VMLINUX_SYMBOL_STR(of_get_property) },
	{ 0x3757c9b, __VMLINUX_SYMBOL_STR(of_get_named_gpio_flags) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0xc2c7fa3a, __VMLINUX_SYMBOL_STR(clk_enable) },
	{ 0xe5e68643, __VMLINUX_SYMBOL_STR(clk_prepare) },
	{ 0x6c8d5ae8, __VMLINUX_SYMBOL_STR(__gpio_get_value) },
	{ 0x38d339db, __VMLINUX_SYMBOL_STR(spi_sync_locked) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0xca16dbe7, __VMLINUX_SYMBOL_STR(regulator_enable) },
	{ 0x6d290445, __VMLINUX_SYMBOL_STR(spi_bus_unlock) },
	{ 0x3acf68cd, __VMLINUX_SYMBOL_STR(spi_setup) },
	{ 0xd631c864, __VMLINUX_SYMBOL_STR(spi_bus_lock) },
	{ 0x60e93ac, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x480fae03, __VMLINUX_SYMBOL_STR(clk_unprepare) },
	{ 0x3ae79c12, __VMLINUX_SYMBOL_STR(clk_disable) },
	{ 0x65d6d0f0, __VMLINUX_SYMBOL_STR(gpio_direction_input) },
	{ 0x1258d9d9, __VMLINUX_SYMBOL_STR(regulator_disable) },
	{ 0xa8f59416, __VMLINUX_SYMBOL_STR(gpio_direction_output) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x4205ad24, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xc2537a8a, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x369e2372, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xde81eb7f, __VMLINUX_SYMBOL_STR(usb_hcd_link_urb_to_ep) },
	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xefea0f6d, __VMLINUX_SYMBOL_STR(usb_hcd_check_unlink_urb) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xbbadc716, __VMLINUX_SYMBOL_STR(usb_hcd_giveback_urb) },
	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x52c5d39b, __VMLINUX_SYMBOL_STR(usb_hcd_unlink_urb_from_ep) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6e439de0, __VMLINUX_SYMBOL_STR(pm_runtime_set_autosuspend_delay) },
	{ 0x17be46f0, __VMLINUX_SYMBOL_STR(devm_kzalloc) },
	{ 0x4cdb3178, __VMLINUX_SYMBOL_STR(ns_to_timeval) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x50878de1, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xa6d930a4, __VMLINUX_SYMBOL_STR(spi_sync) },
	{ 0x73aa1262, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x55409c92, __VMLINUX_SYMBOL_STR(single_open) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x1e3a88fb, __VMLINUX_SYMBOL_STR(trace_seq_printf) },
	{ 0x65d8a3fb, __VMLINUX_SYMBOL_STR(ftrace_raw_output_prep) },
	{ 0x498d293a, __VMLINUX_SYMBOL_STR(trace_buffer_unlock_commit) },
	{ 0xfdd6e493, __VMLINUX_SYMBOL_STR(filter_current_check_discard) },
	{ 0x9621849f, __VMLINUX_SYMBOL_STR(ring_buffer_event_data) },
	{ 0x49b82694, __VMLINUX_SYMBOL_STR(trace_event_buffer_lock_reserve) },
	{ 0x7ecb001b, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0xb0aa3d26, __VMLINUX_SYMBOL_STR(perf_tp_event) },
	{ 0xc917e655, __VMLINUX_SYMBOL_STR(debug_smp_processor_id) },
	{ 0xd788742d, __VMLINUX_SYMBOL_STR(perf_trace_buf_prepare) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x79f49b06, __VMLINUX_SYMBOL_STR(trace_define_field) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

